### ISSUE TITLE
Function getLiveStatus returns "TypeError: argument of type 'NoneType' is not iterable" if a video is not live

### ISSUE THREAD

**Issue by actuallyeunha** [box-archived/vlive-py#21] opened 2021-03-07 20:41 UTC
OS: Windows 10 Pro 20H2
Python 3.9

I'm currently trying to see if the channel is live or not
For testing purposes I'm using pre determined postIds

Here's what I have (entire code):
```
from vlivepy.video import getLiveStatus
from vlivepy.board import getBoardPosts
from vlivepy.connections import postIdToVideoSeq, getPostInfo
import re


# post = getBoardPosts("3498", "FE619", session=None, latest=True)
# print(post)
# nmpost = post["data"][0]
# print(nmpost)
# pnmpost = re.search("\w\W\w\w\w\w\w\w\w\w", str(nmpost)).group()

pnmpost = "0-21484839"

postinfo = getPostInfo(pnmpost)

if postinfo:
	if getPostInfo(pnmpost)['channelCode'] == "FE619":
		videoseq = postIdToVideoSeq(pnmpost, silent=False)
		print(videoseq)
		livestatus = getLiveStatus(videoseq, silent=False)
		print(livestatus)
		if livestatus['liveStatus']:
			if livestatus['liveStatus'] == 'ENDED':
				print("Not live!")
			else:
				print("Live!")
```

This returns:
```
File "C:\Users\%myuser%\AppData\Local\Programs\Python\Python39\lib\site-packages\vlivepy\parser.py", line 145, in response_json_stripper
    if 'data' in parsed_json_dict and len(parsed_json_dict) is 1:
TypeError: argument of type 'NoneType' is not iterable
```

The postId I set there is not a live, I chose it on purpose to test what would happen because I didn't find any other way to see if a post is a live. I expected the function to return None or something similar but... yeah, not the case.

If you need any more information, please feel free to ask

**Comment by box-archived** [comment] 2021-03-07 21:01
This exception caused by VLIVE servers response.
Only at live (or reserved live), Server returns LiveStatus.

I will add more readable exception with message for this situation.

**Comment by box-archived** [comment] 2021-03-07 21:13
also, I powerfully recommend using object.

I suggest you to approach this situation with `vlivepy.OfficialVideoPost` situation.
Like,
```python
import vlivepy

pnmpost = "0-21484839"

# this function returns 'VIDEO' when given postId is Official video
# or returns 'POST' when given postId is just normal post
post_type = vlivepy.postTypeDetector(pnmpost)

if post_type == "VIDEO":
    # vlivepy.OfficialVideoPost also supports init with videoSeq instead of postId
    pnm_video = vlivepy.OfficialVideoPost(pnmpost)

    # `OfficialVideoPost.official_video_type` is the property about it's video type.
    # It returns "LIVE" when self's video type is on air or reserved live
    # It returns "VOD" when self's video type is VOD
    print(pnm_video.official_video_type)

    if pnm_video.official_video_type == "LIVE":
        print("Live!")
    else:
        print("Not live!")
```

It will let you make more exception-safe code

**Comment by box-archived** [comment] 2021-03-07 22:36
I will close this issue with merge PR.
If you need more help, feel free to reopen the issue or write new issue/discussion, anytime!

**Closed** 2021-03-07 22:37 UTC
Labels: bug, question
